kind: Container
type: relational-database
name: Database
description: Stores user registration information, hashed auth credentials, access logs, etc.
technology: Oracle
components:
  UserSchema:
    name: User Schema
