kind: Container
name: Web Application
type: web-application
technology: Java
description: The main static website for the bank, allows users to navigate to the Internet Banking System.
components:
  webApplication:
    name: Web Application
    relationships:
      - type: provides
        target:
          $ref: "./CICS.yaml"
